require("core.plugin_config.color_theme")
require("core.plugin_config.web_devicons")
require("core.plugin_config.lualine")
require("core.plugin_config.bufferline")
require("core.plugin_config.rooter")
require("core.plugin_config.startify")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.aerial")
require("core.plugin_config.lsp_config")
require("core.plugin_config.cmp")
require("core.plugin_config.treesitter")
require('nvim-autopairs').setup {}
