source ~/AppData/Local/nvim/general/settings.vim
source ~/AppData/Local/nvim/vim-plug/plugins.vim
source ~/AppData/Local/nvim/keys/mappings.vim
"source ~/AppData/Local/nvim/themes/onedark.vim
source ~/AppData/Local/nvim/themes/gruvbox.vim
source ~/AppData/Local/nvim/themes/airline.vim
source ~/AppData/Local/nvim/plug-config/coc.vim
source ~/AppData/Local/nvim/plug-config/fzf.vim
source ~/AppData/Local/nvim/plug-config/project-start.vim
source ~/AppData/Local/nvim/plug-config/signify.vim
